//! SystemProbe — cross-platform hardware + OS detection at first run.
//!
//! Phase 1.2 of the OpenWhisper roadmap (research/11-phase-1-tasks.md).
//!
//! ## Purpose
//!
//! The BackendResolver (Phase 1.3) needs to pick the right Whisper model size
//! and LLM cleanup backend for each user's machine. To do that intelligently it
//! needs to know:
//!
//! - OS family and version (macOS 26+ unlocks Apple Foundation Models;
//!   Win 11 24H2+ on Copilot+ unlocks Phi Silica).
//! - CPU architecture (x86_64 vs aarch64 — affects which model binaries we ship).
//! - CPU brand string (e.g. "Apple M3 Pro" tells us we have ANE).
//! - Total RAM (decides quantization tier per decision B9).
//! - Free disk space (decides whether to skip the download or use a smaller
//!   model).
//! - Presence of an NPU (Apple Neural Engine / Windows Copilot+ NPU / etc.).
//! - User locale (initial language pick).
//!
//! See `research/09-auto-provisioning.md §SystemProbe` for the design contract
//! and `§BackendResolver decision matrix` for how this profile is consumed.
//!
//! ## What we deliberately do NOT include
//!
//! - **VRAM enumeration** — would need wgpu or platform-specific COM, both add
//!   significant compile-time cost. Deferred to a later phase once we know we
//!   actually need it (the BackendResolver tier rules don't reference VRAM
//!   numerically — only NPU-present and GPU-present).
//! - **Network speed ping** — deferred. We can adapt download chunk count
//!   reactively from the first download attempt instead.
//! - **Detailed GPU vendor enum** — already exposed by transcribe-rs's
//!   `whisper_cpp::gpu::list_gpu_devices()` (Handy pre-warms it on startup).
//!   The resolver can call that directly when it needs accelerator details.
//!
//! ## Performance
//!
//! `probe()` is intended to be called once at app startup. `sysinfo::System`
//! does a non-trivial OS query so we don't memoize at the module level — the
//! caller decides whether to cache. Typical cost on Win/Mac/Linux: 50–200 ms.

use serde::{Deserialize, Serialize};
use specta::Type;
use sysinfo::{Disks, System};

/// A snapshot of the host system, computed once at startup, consumed by the
/// BackendResolver to pick an STT model + LLM cleanup backend.
///
/// All fields are `pub` so the resolver can pattern-match cleanly. The struct
/// derives `Type` so a TypeScript binding is auto-generated by tauri-specta.
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct SystemProfile {
    /// `"macos"`, `"windows"`, `"linux"`, or another value from
    /// `std::env::consts::OS`.
    pub os_family: String,

    /// Best-effort OS version string, e.g. `"15.2"` on macOS, `"10.0.22631"`
    /// on Windows 11, kernel version on Linux. `None` if the platform query
    /// failed.
    pub os_version: Option<String>,

    /// `"x86_64"`, `"aarch64"`, etc. (from `std::env::consts::ARCH`).
    pub cpu_arch: String,

    /// Vendor + model string, e.g. `"Apple M3 Pro"`, `"AMD Ryzen 9 7950X"`,
    /// `"Intel(R) Core(TM) i7-12700K"`. Empty string if the probe failed.
    pub cpu_brand: String,

    /// Physical core count. Falls back to logical core count if physical isn't
    /// available.
    pub cpu_cores: u32,

    /// Total system RAM in megabytes.
    pub ram_total_mb: u64,

    /// Available (free + cacheable) RAM in megabytes at probe time.
    pub ram_available_mb: u64,

    /// Free disk space on the partition that hosts the OS user data directory,
    /// in megabytes. `None` if no disk was identified.
    pub disk_free_mb: Option<u64>,

    /// True if the CPU is an Apple Silicon chip (M1/M2/M3/M4/...) which
    /// implies the Apple Neural Engine is present.
    pub has_apple_neural_engine: bool,

    /// True if the system is detected as a Windows Copilot+ PC with a Qualcomm
    /// Hexagon / Intel AI Boost / AMD XDNA NPU. Best-effort detection — see
    /// `windows_has_npu()` for the heuristic.
    pub has_windows_npu: bool,

    /// User locale string, e.g. `"en-US"`, `"fr-FR"`. Empty if the platform
    /// API failed.
    pub locale: String,
}

/// Run all probes and return a `SystemProfile`. Idempotent and cheap to call
/// (~50–200 ms). Callers may cache the result.
///
/// Returns `Ok` even when individual probes fail — the failure surfaces as
/// `None` / empty / zero in the relevant field. This is by design: the
/// resolver should always have a profile to work with, even on weird systems.
pub fn probe() -> anyhow::Result<SystemProfile> {
    let mut sys = System::new();
    sys.refresh_memory();
    sys.refresh_cpu_all();

    let cpu_arch = std::env::consts::ARCH.to_string();
    let os_family = std::env::consts::OS.to_string();

    let cpu_brand = sys
        .cpus()
        .first()
        .map(|c| c.brand().to_string())
        .unwrap_or_default();

    // physical_core_count is sometimes unavailable in containers / VMs.
    let cpu_cores = sys
        .physical_core_count()
        .map(|n| n as u32)
        .unwrap_or(sys.cpus().len() as u32);

    let ram_total_mb = sys.total_memory() / 1024 / 1024;
    let ram_available_mb = sys.available_memory() / 1024 / 1024;

    let disk_free_mb = detect_free_disk_space_mb();

    let has_apple_neural_engine = os_family == "macos" && cpu_arch == "aarch64";

    let has_windows_npu = if os_family == "windows" {
        windows_has_npu(&cpu_brand)
    } else {
        false
    };

    Ok(SystemProfile {
        os_family,
        os_version: detect_os_version(),
        cpu_arch,
        cpu_brand,
        cpu_cores,
        ram_total_mb,
        ram_available_mb,
        disk_free_mb,
        has_apple_neural_engine,
        has_windows_npu,
        locale: detect_locale(),
    })
}

/// Largest free space among mounted disks. Used as a coarse proxy for "do we
/// have room to download a 3 GB model?" — we don't try to identify the exact
/// disk hosting the user data dir because that's platform-specific and the
/// "any disk with enough room" heuristic is good enough for the resolver.
fn detect_free_disk_space_mb() -> Option<u64> {
    let disks = Disks::new_with_refreshed_list();
    disks
        .iter()
        .map(|d| d.available_space() / 1024 / 1024)
        .max()
}

/// Best-effort OS version detection.
///
/// macOS: parses `sw_vers -productVersion`. Falls back to `uname -r` for the
/// Darwin kernel version on failure.
///
/// Windows: reads `OS Version` from `cmd /c ver`. We avoid the registry hop
/// to keep this dependency-free.
///
/// Linux: parses `/etc/os-release` `VERSION_ID` if available; otherwise the
/// uname release.
fn detect_os_version() -> Option<String> {
    #[cfg(target_os = "macos")]
    {
        use std::process::Command;
        let out = Command::new("sw_vers")
            .arg("-productVersion")
            .output()
            .ok()?;
        let s = String::from_utf8(out.stdout).ok()?;
        let trimmed = s.trim();
        if trimmed.is_empty() {
            None
        } else {
            Some(trimmed.to_string())
        }
    }

    #[cfg(target_os = "windows")]
    {
        use std::process::Command;
        let out = Command::new("cmd").args(["/c", "ver"]).output().ok()?;
        let s = String::from_utf8(out.stdout).ok()?;
        // `ver` returns something like "Microsoft Windows [Version 10.0.22631.4317]"
        let version = s.split('[').nth(1)?.split(']').next()?;
        let trimmed = version.trim().trim_start_matches("Version ").to_string();
        if trimmed.is_empty() {
            None
        } else {
            Some(trimmed)
        }
    }

    #[cfg(target_os = "linux")]
    {
        use std::fs;
        if let Ok(contents) = fs::read_to_string("/etc/os-release") {
            for line in contents.lines() {
                if let Some(rest) = line.strip_prefix("VERSION_ID=") {
                    return Some(rest.trim_matches('"').to_string());
                }
            }
        }
        None
    }

    #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "linux")))]
    {
        None
    }
}

/// Best-effort user locale detection. Reads `LANG` / `LC_ALL` env vars first
/// (most reliable on Unix), falls back to platform-specific APIs.
///
/// Returns IETF-style `language-REGION` codes (e.g. `"en-US"`, `"fr-FR"`) when
/// possible, or an empty string if everything failed.
fn detect_locale() -> String {
    // Unix-style env vars work on macOS and Linux out of the box.
    for var in ["LANG", "LC_ALL", "LC_MESSAGES"] {
        if let Ok(val) = std::env::var(var) {
            // POSIX locales look like "en_US.UTF-8" — normalize to "en-US".
            let normalized = val
                .split('.')
                .next()
                .unwrap_or("")
                .replace('_', "-");
            if !normalized.is_empty() && normalized != "C" && normalized != "POSIX" {
                return normalized;
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        use std::process::Command;
        // `Get-Culture` returns an object whose `Name` property is the
        // BCP-47-ish locale ("en-US", "fr-FR", ...). PowerShell is always
        // available on Win10+.
        if let Ok(out) = Command::new("powershell")
            .args(["-NoProfile", "-Command", "(Get-Culture).Name"])
            .output()
        {
            if let Ok(s) = String::from_utf8(out.stdout) {
                let trimmed = s.trim().to_string();
                if !trimmed.is_empty() {
                    return trimmed;
                }
            }
        }
    }

    String::new()
}

/// Heuristic NPU detection on Windows. Returns true if the CPU brand contains
/// a known NPU-equipped chip family marker:
///
/// - Qualcomm Snapdragon X / X Elite (Hexagon NPU)
/// - Intel Core Ultra series 2 / Lunar Lake (NPU 4)
/// - AMD Ryzen AI / Ryzen 7040+ / Phoenix / Hawk / Strix (XDNA NPU)
///
/// This is intentionally conservative — false negatives are fine (the user can
/// override in Settings); false positives would route the cleanup pipeline to a
/// nonexistent NPU and fall back loudly. Update the heuristic when new families
/// ship.
#[allow(unused_variables)]
fn windows_has_npu(cpu_brand: &str) -> bool {
    let brand = cpu_brand.to_lowercase();

    // Qualcomm Snapdragon X series (Copilot+ launch hardware).
    if brand.contains("snapdragon") && brand.contains('x') {
        return true;
    }

    // Intel Core Ultra series (Meteor Lake, Lunar Lake, Arrow Lake).
    if brand.contains("core(tm) ultra") || brand.contains("core ultra") {
        return true;
    }

    // AMD Ryzen AI / Phoenix / Hawk Point / Strix Point.
    if brand.contains("ryzen ai") || brand.contains("ryzen") && brand.contains("ai") {
        return true;
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The most important guarantee: `probe()` never panics, even in weird
    /// containerized / VM environments. CI runs on GitHub-hosted runners that
    /// hit some of those.
    #[test]
    fn probe_returns_a_profile() {
        let profile = probe().expect("probe should not fail");
        assert!(
            !profile.os_family.is_empty(),
            "OS family should never be empty"
        );
        assert!(
            !profile.cpu_arch.is_empty(),
            "CPU arch should never be empty"
        );
    }

    /// Sanity range: RAM should be > 0 on any machine that can build this code.
    #[test]
    fn probe_detects_some_ram() {
        let profile = probe().expect("probe should not fail");
        assert!(
            profile.ram_total_mb > 0,
            "total RAM should be greater than zero on any real system"
        );
        assert!(
            profile.ram_available_mb <= profile.ram_total_mb,
            "available RAM ({}) should not exceed total ({})",
            profile.ram_available_mb,
            profile.ram_total_mb
        );
    }

    /// Sanity: at least one CPU core (impossible to compile this otherwise).
    #[test]
    fn probe_detects_cpu_cores() {
        let profile = probe().expect("probe should not fail");
        assert!(profile.cpu_cores >= 1, "should detect at least one core");
    }

    /// OS family is one of the known values for the platforms we target.
    /// Unknown values are not fatal but indicate we may need to extend support.
    #[test]
    fn probe_reports_known_os_family() {
        let profile = probe().expect("probe should not fail");
        assert!(
            matches!(
                profile.os_family.as_str(),
                "macos" | "windows" | "linux" | "ios" | "android" | "freebsd"
            ),
            "unexpected os_family '{}': probe is running on a platform we haven't accounted for",
            profile.os_family
        );
    }

    /// On macOS, Apple Silicon detection should fire on aarch64 only.
    #[test]
    fn apple_neural_engine_only_set_on_apple_silicon() {
        let profile = probe().expect("probe should not fail");
        if profile.has_apple_neural_engine {
            assert_eq!(profile.os_family, "macos");
            assert_eq!(profile.cpu_arch, "aarch64");
        }
    }

    /// Windows NPU detection is heuristic — exercise the brand-matching logic
    /// directly so it doesn't depend on the test host having an NPU.
    #[test]
    fn windows_npu_heuristic_matches_expected_brands() {
        assert!(windows_has_npu("Snapdragon X Elite"));
        assert!(windows_has_npu("Snapdragon X Plus"));
        assert!(windows_has_npu("Intel(R) Core(TM) Ultra 9 285H"));
        assert!(windows_has_npu("Intel Core Ultra 7 165H"));
        assert!(windows_has_npu("AMD Ryzen AI 9 HX 370"));
    }

    /// Common consumer chips should NOT trigger an NPU detection.
    #[test]
    fn windows_npu_heuristic_does_not_false_positive() {
        assert!(!windows_has_npu("Intel(R) Core(TM) i7-12700K"));
        assert!(!windows_has_npu("AMD Ryzen 9 7950X"));
        assert!(!windows_has_npu("Intel Xeon E5-2670"));
        assert!(!windows_has_npu(""));
    }
}
